In [2]:
import numpy as np
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
I_mat = np.eye(3)
I_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
odd_nums = arr[arr % 2 == 1]

print(odd_nums)

[1 3 5 7 9]
