In [ ]:
import numpy as np
arr = np.arange(1, 31).reshape(6, 5)
print(arr)
print("----------")
print(arr[2:4,0:2])
print("----------")
arr_task3 = np.zeros_like(arr)
arr_task3[0,1] = 2
arr_task3[1,2] = 8
arr_task3[2,3] = 14
arr_task3[3,4] = 20
print(arr_task3)
print("----------")
arr_task4 = np.zeros_like(arr)
arr_task4[0, 3:5] = arr[0, 3:5]
arr_task4[4, 3:5] = arr[4, 3:5]
arr_task4[5, 3:5] = arr[5, 3:5]
print(arr_task4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
----------
[[11 12]
 [16 17]]
----------
[[ 0  2  0  0  0]
 [ 0  0  8  0  0]
 [ 0  0  0 14  0]
 [ 0  0  0  0 20]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
----------
[[ 0  0  0  4  5]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0 24 25]
 [ 0  0  0 29 30]]
