In [3]:
import numpy as np

arr1D = np.arange(1, 13)          
arr2D = arr1D.reshape(3, 4)       
print(arr2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
random_array = np.random.rand(5, 5)
print(random_array)

[[0.04444729 0.67225916 0.90586356 0.69375836 0.8316474 ]
 [0.62939087 0.1041564  0.10087448 0.96246805 0.38511815]
 [0.55270396 0.68001851 0.74476917 0.69752684 0.03637168]
 [0.89764932 0.82807166 0.14639888 0.35177018 0.82651295]
 [0.59227116 0.71342895 0.90673166 0.33424373 0.62978056]]


In [5]:
mat_1 = np.random.rand(5, 3)
mat_2 = np.random.rand(3, 2)
matrix_product = np.dot(mat_1, mat_2)
print(matrix_product)

[[0.74234299 0.47707927]
 [0.56824535 0.56828359]
 [0.52962391 0.73629559]
 [1.13903772 1.44666896]
 [0.59844778 0.84563235]]


In [6]:
arr = np.arange(0, 11)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
